### ISSUE TITLE
Can't locate Test2/V0.pm in @INC

### ISSUE THREAD

**Issue by eserte** [lancew/Webservice-Judobase#11]
t/00-Basic.t fails if Test2::V0 is not yet installed:
```
PERL_DL_NONLAZY=1 "/usr/local/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Can't locate Test2/V0.pm in @INC (you may need to install the Test2::V0 module) (@INC contains: ...  .) at t/00-Basic.t line 1.
BEGIN failed--compilation aborted at t/00-Basic.t line 1.
t/00-Basic.t ..................... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by lancew** [comment]
Thanks for raising this!!
Yep in changing my dist.ini I've failed to include the prereq for Test2.

**Comment by lancew** [comment]
Looking at http://matrix.cpantesters.org/?dist=Webservice-Judobase+0.07 things look healthy and http://www.cpantesters.org/cpan/report/7b9cdbe8-aa1c-11ec-a56f-347f1f24ea8f specifically.
Thanks for raising the issue!
