### ISSUE TITLE
contains copy of itself

### ISSUE THREAD

**Issue by chorny** [lancew/Webservice-Judobase#5]
Extra directory Webservice-Judobase-0.001 and file Webservice-Judobase-0.001.tar.gz .
See https://metacpan.org/source/LANCEW/Webservice-Judobase-0.001-TRIAL

**Comment by lancew** [comment]
Thx... Shall clean it up. 
Glad I did as a -TRIAL. :-)

**Comment by lancew** [comment]
Should have closed this long ago, apologies @chorny
